# Generated by Django 5.2.8 on 2026-01-07 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_secondary_phone_number"),
        ("users", "0002_user_secondary_phone_number"),
    ]

    operations = []
