# Generated by Django 5.2.8 on 2025-12-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='college',
            field=models.CharField(default='كلية تقنية المعلومات', max_length=100, verbose_name='الكلية'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='link_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='كود الربط'),
        ),
    ]
