// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSCPWbtxmXJzTwGwj4OZDba3r3JaCuAlU',
    appId: '1:490797315957:web:1c88cd379ac1bc7274053c',
    messagingSenderId: '490797315957',
    projectId: 'revealapp-8af3f',
    authDomain: 'revealapp-8af3f.firebaseapp.com',
    storageBucket: 'revealapp-8af3f.firebasestorage.app',
    measurementId: 'G-E1KPT4VX1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs2zvNg7O3Be2YssEljNYD7fxFp4DsR9I',
    appId: '1:490797315957:android:1749b54493db54ee74053c',
    messagingSenderId: '490797315957',
    projectId: 'revealapp-8af3f',
    storageBucket: 'revealapp-8af3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB0Bf7boXLziJH218O_ABhCYzLIdeY520',
    appId: '1:490797315957:ios:6874f2fce59de5fb74053c',
    messagingSenderId: '490797315957',
    projectId: 'revealapp-8af3f',
    storageBucket: 'revealapp-8af3f.firebasestorage.app',
    iosBundleId: 'edu.zliten.university.revealApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB0Bf7boXLziJH218O_ABhCYzLIdeY520',
    appId: '1:490797315957:ios:6874f2fce59de5fb74053c',
    messagingSenderId: '490797315957',
    projectId: 'revealapp-8af3f',
    storageBucket: 'revealapp-8af3f.firebasestorage.app',
    iosBundleId: 'edu.zliten.university.revealApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSCPWbtxmXJzTwGwj4OZDba3r3JaCuAlU',
    appId: '1:490797315957:web:1c88cd379ac1bc7274053c',
    messagingSenderId: '490797315957',
    projectId: 'revealapp-8af3f',
    authDomain: 'revealapp-8af3f.firebaseapp.com',
    storageBucket: 'revealapp-8af3f.firebasestorage.app',
    measurementId: 'G-E1KPT4VX1B',
  );
}
