# Generated by Django 5.2.8 on 2025-12-12 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cafe',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='صورة المقصف'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المقصف'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_cafe', to=settings.AUTH_USER_MODEL, verbose_name='مدير المقصف'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.cafe', verbose_name='المقصف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='رقم الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PREPARING', 'جاري التحضير'), ('READY', 'جاهز للاستلام'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.cafe', verbose_name='المقصف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متاح للطلب'),
        ),
    ]
