# Generated by Django 5.2.8 on 2025-12-20 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'تصنيف', 'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.AddField(
            model_name='cafe',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3, verbose_name='التقييم'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.IntegerField(default=10, verbose_name='عدد المقيمين'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cafes/', verbose_name='شعار الكلية'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الكلية/المقهى'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_cafe', to=settings.AUTH_USER_MODEL, verbose_name='مسؤول الكلية'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم التصنيف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.cafe', verbose_name='الكلية'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PREPARING', 'قيد التحضير'), ('READY', 'جاهز للاستلام'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغى')], default='PENDING', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر الوحدة عند الطلب'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.cafe', verbose_name='الكلية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج'),
        ),
        migrations.DeleteModel(
            name='RestaurantCard',
        ),
    ]
