# Generated by Django 6.0 on 2025-12-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_orderitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('ACCEPTED', '?? ???? ?????'), ('PREPARING', 'قيد التحضير'), ('READY', 'جاهز للاستلام'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغى')], default='PENDING', max_length=20, verbose_name='الحالة'),
        ),
    ]
