# Generated by Django 5.2.8 on 2026-01-07 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_orderitem_options_alter_order_status"),
        ("core", "0006_alter_order_status"),
    ]

    operations = []
